[build]
  publish = "dist/public"
  command = "vite build --config vite.config.prod.ts && esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"